# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radiobutton_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 163)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setStyleSheet("QGroupBox#groupBox{\n"
                                    "font-size: 15px;\n"
                                    "font-weight: bold;\n"
                                    "padding: 15px;\n"
                                    "padding-top: 30px;\n"
                                    "}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.football_radio = QtWidgets.QRadioButton(self.groupBox)
        self.football_radio.setObjectName("football_radio")
        self.football_radio.setIcon(QIcon('./icons/schedule.png'))
        self.football_radio.setChecked(True)
        self.football_radio.toggled.connect(self.radio_clicked)
        self.horizontalLayout.addWidget(self.football_radio)

        self.soccer_radio = QtWidgets.QRadioButton(self.groupBox)
        self.soccer_radio.setObjectName("soccer_radio")
        self.soccer_radio.setIcon(QIcon('./icons/clinic.png'))
        self.soccer_radio.toggled.connect(self.radio_clicked)
        self.horizontalLayout.addWidget(self.soccer_radio)

        self.tennis_radio = QtWidgets.QRadioButton(self.groupBox)
        self.tennis_radio.setObjectName("tennis_radio")
        self.tennis_radio.setIcon(QIcon('./icons/medicine.png'))
        self.tennis_radio.toggled.connect(self.radio_clicked)
        self.horizontalLayout.addWidget(self.tennis_radio)

        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.selection_label = QtWidgets.QLabel(Dialog)
        self.selection_label.setStyleSheet("QLabel#selection_label{\n"
                                           "font-size: 15px;\n"
                                           "font-weight: bold;\n"
                                           "}")
        self.selection_label.setObjectName("selection_label")
        self.verticalLayout.addWidget(self.selection_label)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_clicked(self):
        radio = self.sender()
        if radio.isChecked():
            self.selection_label.setText(f'You have selected: {radio.text()}')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Radio button and group box"))
        self.groupBox.setTitle(_translate("Dialog", "What is your favorite sport?"))
        self.football_radio.setText(_translate("Dialog", "Football"))
        self.soccer_radio.setText(_translate("Dialog", "Soccer"))
        self.tennis_radio.setText(_translate("Dialog", "Tennis"))
        self.selection_label.setText(_translate("Dialog", "You have selected: Football"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
